<?php
session_name("pay-man");
session_set_cookie_params ( 0, '/',  'pay-man.in');
session_start();
define('CHECK_USER_EXISTENCE','SELECT USER_ID FROM user_details WHERE USERNAME = ? AND PASSWORD = ? AND ACTIVE = 1');
define('CHECK_PERSON_EXISTENCE','SELECT PERSON_ID FROM person_details WHERE PERSON_NAME = ?');
define('INSERT_PERSON_PAYMENT',"INSERT INTO payment_details(PAYMENT_ID,CATEGORY_NAME,PERSON_ID,AMOUNT,REMARK) VALUES(?,'PERSON',?,?,?)");
define('INSERT_PERSON','INSERT INTO person_details(PERSON_ID,PERSON_NAME) VALUES(?,?)');
define('LOAD_TOTAL_PERSON_PAYMENT','SELECT PER.PERSON_ID,PER.PERSON_NAME,(CASE WHEN SUM(PAY.AMOUNT) IS NULL THEN 0 ELSE SUM(PAY.AMOUNT) END) AS TOTAL FROM person_details PER LEFT OUTER JOIN payment_details PAY ON PER.PERSON_ID = PAY.PERSON_ID GROUP BY PER.PERSON_ID ORDER BY PER.PERSON_NAME');
define('LOAD_MONTHLY_PERSON_PAYMENT','SELECT PER.PERSON_ID,PER.PERSON_NAME,(CASE WHEN SUM(PAY.AMOUNT) IS NULL THEN 0 ELSE SUM(PAY.AMOUNT) END) AS TOTAL FROM person_details PER LEFT OUTER JOIN payment_details PAY ON PER.PERSON_ID = PAY.PERSON_ID AND MONTH(PAY.DATE) = ? AND YEAR(PAY.DATE) = ? GROUP BY PER.PERSON_ID ORDER BY PER.PERSON_NAME');
define('LOAD_MONTHLY_INDIVIDUAL_PERSON_PAYMENT','SELECT DATE,AMOUNT,REMARK FROM payment_details WHERE PERSON_ID = ? AND MONTH(DATE) = ? AND YEAR(DATE) = ? ORDER BY DATE DESC');
define('LOAD_RECENT_PERSON_PAYMENT',"SELECT PD.DATE,PER.PERSON_ID,PER.PERSON_NAME,PD.AMOUNT FROM person_details PER LEFT OUTER JOIN payment_details PD ON PER.PERSON_ID = PD.PERSON_ID AND PD.CATEGORY_NAME = 'PERSON' ORDER BY DATE DESC LIMIT 0,100");

define('CHECK_ITEM_EXISTENCE','SELECT ITEM_ID FROM item_details WHERE ITEM_NAME = ?');
define('INSERT_ITEM_PAYMENT',"INSERT INTO payment_details(PAYMENT_ID,CATEGORY_NAME,ITEM_ID,AMOUNT,GST) VALUES(?,'ITEM',?,?,?)");
define('INSERT_ITEM','INSERT INTO item_details(ITEM_ID,ITEM_NAME) VALUES(?,?)');
define('LOAD_TOTAL_ITEM_PAYMENT',"SELECT ID.ITEM_ID,ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID LEFT OUTER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' ORDER BY DATE DESC LIMIT 0,100");
define('LOAD_MONTHLY_ITEM_PAYMENT',"SELECT ID.ITEM_ID,ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' AND MONTH(PD.DATE) = ? AND YEAR(PD.DATE) = ? ORDER BY DATE DESC");
define('LOAD_PER_ITEM_PAYMENT',"SELECT ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' AND PD.ITEM_ID = ? ORDER BY DATE DESC");
?>