<?php
session_name("pay-man");
session_set_cookie_params ( 0, '/',  'pay-man.in');
session_start();
define('CHECK_USER_EXISTENCE','SELECT USER_ID FROM user_details WHERE USERNAME = ? AND PASSWORD = ? AND ACTIVE = 1');
define('CHANGE_PASSWORD','UPDATE user_details SET PASSWORD = ? WHERE USER_ID = ?');
define('CHECK_PERSON_EXISTENCE','SELECT PERSON_ID FROM person_details WHERE PERSON_NAME = ?');
define('INSERT_PERSON_PAYMENT',"INSERT INTO payment_details(PAYMENT_ID,CATEGORY_NAME,PERSON_ID,AMOUNT,REMARK,DATE) VALUES(?,'PERSON',?,?,?,?)");
define('INSERT_PERSON','INSERT INTO person_details(PERSON_ID,PERSON_NAME) VALUES(?,?)');
define('LOAD_TOTAL_PERSON_PAYMENT','SELECT PER.PERSON_ID,PER.PERSON_NAME,(CASE WHEN SUM(PAY.AMOUNT) IS NULL THEN 0 ELSE SUM(PAY.AMOUNT) END) AS TOTAL FROM person_details PER INNER JOIN payment_details PAY ON PER.PERSON_ID = PAY.PERSON_ID AND PAY.DELETED = 0 GROUP BY PER.PERSON_ID ORDER BY PER.PERSON_NAME LIMIT ?,?');
define('LOAD_MONTHLY_PERSON_PAYMENT','SELECT PER.PERSON_ID,PER.PERSON_NAME,(CASE WHEN SUM(PAY.AMOUNT) IS NULL THEN 0 ELSE SUM(PAY.AMOUNT) END) AS TOTAL FROM person_details PER INNER JOIN payment_details PAY ON PER.PERSON_ID = PAY.PERSON_ID AND MONTH(PAY.DATE) = ? AND YEAR(PAY.DATE) = ? AND PAY.DELETED = 0 GROUP BY PER.PERSON_ID ORDER BY PER.PERSON_NAME LIMIT ?,?');
define('LOAD_MONTHLY_INDIVIDUAL_PERSON_PAYMENT','SELECT DATE,AMOUNT,REMARK FROM payment_details WHERE PERSON_ID = ? AND MONTH(DATE) = ? AND YEAR(DATE) = ? AND DELETED = 0 ORDER BY DATE DESC LIMIT ?,?');
define('LOAD_RECENT_PERSON_PAYMENT',"SELECT PD.PAYMENT_ID,PD.DATE,PER.PERSON_ID,PER.PERSON_NAME,PD.AMOUNT FROM person_details PER INNER JOIN payment_details PD ON PER.PERSON_ID = PD.PERSON_ID AND PD.CATEGORY_NAME = 'PERSON' AND PD.DELETED = 0 ORDER BY PD.PAYMENT_ID DESC LIMIT ?,?");
define('LOAD_RECENT_INDIVIDUAL_PERSON_PAYMENT',"SELECT PD.DATE,PD.AMOUNT,PD.REMARK FROM person_details PER INNER JOIN payment_details PD ON PER.PERSON_ID = PD.PERSON_ID AND PD.PERSON_ID = ? AND PD.CATEGORY_NAME = 'PERSON' AND PD.DELETED = 0 ORDER BY DATE DESC  LIMIT ?,?");

define('CHECK_ITEM_EXISTENCE','SELECT ITEM_ID FROM item_details WHERE ITEM_NAME = ?');
define('INSERT_ITEM_PAYMENT',"INSERT INTO payment_details(PAYMENT_ID,CATEGORY_NAME,ITEM_ID,AMOUNT,GST,DATE) VALUES(?,'ITEM',?,?,?,?)");
define('INSERT_ITEM','INSERT INTO item_details(ITEM_ID,ITEM_NAME) VALUES(?,?)');
define('LOAD_TOTAL_ITEM_PAYMENT',"SELECT PD.PAYMENT_ID,ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' AND PD.DELETED = 0 ORDER BY PD.PAYMENT_ID DESC LIMIT 0,100");
define('LOAD_MONTHLY_ITEM_PAYMENT',"SELECT ID.ITEM_ID,ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' AND MONTH(PD.DATE) = ? AND YEAR(PD.DATE) = ? AND PD.DELETED = 0 ORDER BY DATE DESC");
define('LOAD_PER_ITEM_PAYMENT',"SELECT PD.PAYMENT_ID,ID.ITEM_NAME,PD.AMOUNT,PD.GST,PD.DATE FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.CATEGORY_NAME = 'ITEM' AND PD.PAYMENT_ID = ? AND PD.DELETED = 0 ORDER BY DATE DESC");
define('SEARCH_PERSON',"SELECT PERSON_ID,PERSON_NAME FROM person_details WHERE PERSON_NAME LIKE CONCAT('%',?,'%') ORDER BY PERSON_NAME LIMIT 0,100");
define('SEARCH_ITEM',"SELECT ITEM_ID,ITEM_NAME FROM item_details WHERE ITEM_NAME LIKE CONCAT('%',?,'%') ORDER BY ITEM_NAME LIMIT 0,100");
define('DELETE_PAYMENT',"UPDATE payment_details SET DELETED = 1 WHERE PAYMENT_ID = ?");
define('LOAD_MONTHLY_INDIVIDUAL_ITEM_PAYMENT','SELECT DATE,AMOUNT,GST FROM payment_details WHERE ITEM_ID = ? AND MONTH(DATE) = ? AND YEAR(DATE) = ? AND DELETED = 0 ORDER BY DATE DESC');
define('LOAD_RECENT_INDIVIDUAL_ITEM_PAYMENT',"SELECT PD.DATE,PD.AMOUNT,PD.GST FROM item_details ID INNER JOIN payment_details PD ON ID.ITEM_ID = PD.ITEM_ID AND PD.ITEM_ID = ? AND PD.CATEGORY_NAME = 'ITEM' AND PD.DELETED = 0 ORDER BY DATE DESC LIMIT 0,100");
?>